import type { DirectorPlanInput } from "../types";

export function buildDirectorPlanPrompt(input: DirectorPlanInput): string {
  const existingSkills = (input.existingCharacterSkills || [])
    .map((character) => `${character.characterName}：${character.skills.map((skill) => `${skill.name}（${skill.description}）`).join("；")}`)
    .join("\n");
  return [
    "你是一名动画短片导演和制片数据设计师。",
    "请把锁定剧本润色并拆解为可编辑、可验证的导演制作计划。",
    "",
    "【项目设定】",
    `画风：${input.artStyle}`,
    `作品标签：${input.tags.join("、") || "无"}`,
    `画幅：${input.aspectRatio}`,
    `语言：${input.language}`,
    `用户时长偏好（仅供参考，不要求凑满）：${input.targetDuration}`,
    "",
    "【已有角色固定技能（剧情涉及时必须沿用）】",
    existingSkills || "无",
    "这里仅提供技能名称和技能说明。不得改变已有技能的效果、机制或限制；剧情没有使用某项技能时，不要强行加入。",
    "",
    "【锁定剧本】",
    input.lockedScript,
    "",
    "【拆解规则】",
    "1. 输出 polishedScript、summary、assets、clips。",
    "2. assets 必须区分 character、scene、prop，每项拥有稳定且唯一的 id。",
    "2.1 如果锁定剧本包含“出场人物”名单，名单中的每个名字必须各生成且只生成一个 character；不得遗漏、重命名、互换名字与描述，也不得用不同 id 重复同一角色。",
    "2.2 每个 character 必须填写 characterProfile：height（身高）、weight（体重）和 skills（固定技能）。剧本没有明确数值时写“未设定”，不得擅自编造；skills 仅收录剧本明确展示或说明的长期能力，没有则返回空数组。",
    "3. 每个镜头包含景别、运镜、时长、动作、视觉提示词、音频项和资产引用。",
    "4. 镜头资产只能通过 type + id 引用，不能只使用名称；同名不同类别是不同资产。",
    "5. 视觉提示词必须服从项目画风，并明确人物、场景、构图、光线和情绪。",
    "5.1 每个 scene 资产必须填写 sceneContinuity：time（时段）、weather（天气）、lighting（主光线及方向）、palette（统一色卡）。同一天且剧情没有明确变化的场景必须保持相同天气、太阳方向和基础色卡。",
    "6. 不添加锁定剧本没有依据的重要角色、道具或剧情结局。",
    "7. 必须根据剧情内容、对白长度、动作复杂度和叙事节奏，自主估算每个镜头的合理时长；用户时长偏好不是硬性总时长。",
    "7.1 全片实际总时长可以短于或长于用户时长偏好；不得为了凑满偏好时长而重复内容、拖长空镜头或硬拆镜头。",
    "7.2 镜头数量也由剧情需要决定；只保留讲清故事所必需的镜头，每个 duration 必须填写可执行的秒数，后续允许用户逐镜头修改。",
    "8. summary、素材 description、镜头 action 和 visualPrompt 必须简洁，避免重复剧本原文。",
    "",
    "【必须严格遵循的 JSON 结构】",
    "{",
    '  "polishedScript": "润色后的完整剧本文本",',
    '  "summary": "一段简短故事概要",',
    '  "assets": [',
    '    { "id": "character-1", "type": "character", "name": "角色名", "description": "简短设定", "tags": ["标签"], "characterProfile": { "height": "180cm", "weight": "75kg", "skills": [{ "id": "skill-1", "name": "技能名", "description": "固定能力与用途", "visualPrompt": "技能发动时的颜色、形态、光效与范围" }] } },',
    '    { "id": "scene-1", "type": "scene", "name": "场景名", "description": "简短设定", "tags": ["标签"], "sceneContinuity": { "time": "下午", "weather": "晴朗少云", "lighting": "左前方暖色斜射光，阴影方向统一", "palette": "冷灰废墟、低饱和青绿、暖金高光" } }',
    "  ],",
    '  "clips": [',
    '    { "id": "clip-1", "title": "片段标题", "summary": "片段概要", "shots": [',
    '      { "id": "shot-1", "title": "镜头标题", "shotSize": "中景 MS", "cameraMovement": "缓慢推进", "duration": 8, "action": "动作", "visualPrompt": "简洁画面提示词", "audioItems": [{ "type": "环境音", "content": "环境声" }], "assets": [{ "type": "character", "id": "character-1" }, { "type": "scene", "id": "scene-1" }] }',
    "    ] }",
    "  ]",
    "}",
    "assets 必须是单一数组，不得拆成 characters/scenes/props 对象。clips 每项必须包含 shots 数组。summary 必须是字符串。",
    "",
    "只能输出 JSON，不要 Markdown 代码块、解释、前言或结语。",
  ].join("\n");
}
