import type { DirectorPlanInput } from "../types";

export function buildDirectorPlanPrompt(input: DirectorPlanInput): string {
  return [
    "你是一名动画短片导演和制片数据设计师。",
    "请把锁定剧本润色并拆解为可编辑、可验证的导演制作计划。",
    "",
    "【项目设定】",
    `画风：${input.artStyle}`,
    `作品标签：${input.tags.join("、") || "无"}`,
    `画幅：${input.aspectRatio}`,
    `语言：${input.language}`,
    `目标时长：${input.targetDuration}`,
    "",
    "【锁定剧本】",
    input.lockedScript,
    "",
    "【拆解规则】",
    "1. 输出 polishedScript、summary、assets、clips。",
    "2. assets 必须区分 character、scene、prop，每项拥有稳定且唯一的 id。",
    "3. 每个镜头包含景别、运镜、时长、动作、视觉提示词、音频项和资产引用。",
    "4. 镜头资产只能通过 type + id 引用，不能只使用名称；同名不同类别是不同资产。",
    "5. 视觉提示词必须服从项目画风，并明确人物、场景、构图、光线和情绪。",
    "6. 不添加锁定剧本没有依据的重要角色、道具或剧情结局。",
    "7. 全片总镜头数限制在 8–12 个；用较长的单镜头覆盖目标时长，不得为了凑时长拆出大量短镜头。",
    "8. summary、素材 description、镜头 action 和 visualPrompt 必须简洁，避免重复剧本原文。",
    "",
    "【必须严格遵循的 JSON 结构】",
    "{",
    '  "polishedScript": "润色后的完整剧本文本",',
    '  "summary": "一段简短故事概要",',
    '  "assets": [',
    '    { "id": "character-1", "type": "character", "name": "角色名", "description": "简短设定", "tags": ["标签"] },',
    '    { "id": "scene-1", "type": "scene", "name": "场景名", "description": "简短设定", "tags": ["标签"] }',
    "  ],",
    '  "clips": [',
    '    { "id": "clip-1", "title": "片段标题", "summary": "片段概要", "shots": [',
    '      { "id": "shot-1", "title": "镜头标题", "shotSize": "中景 MS", "cameraMovement": "缓慢推进", "duration": 8, "action": "动作", "visualPrompt": "简洁画面提示词", "audioItems": [{ "type": "环境音", "content": "环境声" }], "assets": [{ "type": "character", "id": "character-1" }, { "type": "scene", "id": "scene-1" }] }',
    "    ] }",
    "  ]",
    "}",
    "assets 必须是单一数组，不得拆成 characters/scenes/props 对象。clips 每项必须包含 shots 数组。summary 必须是字符串。",
    "",
    "只能输出 JSON，不要 Markdown 代码块、解释、前言或结语。",
  ].join("\n");
}
